directory: ~/syncthing/sync/music
library: ~/syncthing/sync/music/beets.db

plugins:
  - musicbrainz
  - fetchart

import:
  incremental: yes

fetchart:
  max_filesize: 10485760
  high_resolution: no
  maxwidth: 250
